workflows:
  lotto-app:
    name: Lotto World Pro
    environment:
      groups:
        - keystore_credentials
      vars:
        BUILD_NUMBER: 6
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Run tests
        script: flutter test
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
