# codemagic.yaml - Lotto World Pro Android Build
workflows:
  android-release:
    name: Android Release Build
    environment:
      groups:
        # F체ge diese Gruppe in Codemagic UI hinzu f체r Signierung:
        # - keystore_credentials
      vars:
        BUILD_NUMBER: 7
      flutter: "3.22.0"  # Spezifische Version f체r Stabilit채t
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release --build-number=$BUILD_NUMBER
      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release --build-number=$BUILD_NUMBER
    artifacts:
      - build/app/outputs/**/*.apk
      - build/app/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - funatiker68@gmail.com
