workflows:
  android-release:
    name: Android Release APK
    environment:
      flutter: "3.22.0"
    scripts:
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - funatiker68@gmail.com
